<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <LangVersion>10</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
        <DebugType>none</DebugType>
        <OutputPath>$(BuildOutputDir)/patchers</OutputPath>
        <GameDeployPath>$(NuclearOptionPatcherDeployPath)</GameDeployPath>
        <RootNamespace>NOVRPatcher</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="AssetsTools.NET" Version="3.0.5" />
        <Reference Include="$(NuclearOptionFallbackLibDir)/*.dll">
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NOVR.XR.Management\NOVR.XR.Management.csproj" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\NOVR.XR.OpenXR\NOVR.XR.OpenXR.csproj" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="CopyToGame\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="classdata.tpk">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mono.Cecil" Version="0.11.6" IncludeAssets="compile" />
    </ItemGroup>

    <Target Name="CopyXrAssembliesToPatcherPayload" BeforeTargets="StageGameLayout">
        <ItemGroup>
            <XrAssemblyPayload Include="$(BuildOutputDir)/plugins/Unity.XR.Management.dll" />
            <XrAssemblyPayload Include="$(BuildOutputDir)/plugins/Unity.XR.OpenXR.dll" />
        </ItemGroup>

        <MakeDir Directories="$(TargetDir)CopyToGame/Data/Managed" />
        <Copy SourceFiles="@(XrAssemblyPayload)" DestinationFiles="@(XrAssemblyPayload->'$(TargetDir)CopyToGame/Data/Managed/%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>
</Project>
